### ISSUE TITLE
Отсортируем по алфавиту

### ISSUE THREAD

**Issue by d13mon** [danilsatchkov/yandex_course#24]
https://github.com/danilsatchkov/yandex_course/blob/accae30f69288e7e1ba15b68de12a802049656e1/Yandex_course/Error_handling.cpp#L1-L9

**Comment by danilsatchkov** [comment]
Можете пояснить что здесь, никакого текста нет?
 
From: Dmitrii Kuchinskii ***@***.***> 
Sent: Sunday, May 16, 2021 2:36 PM
To: danilsatchkov/yandex_course ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [danilsatchkov/yandex_course] Отсортируем по алфавиту (#24)
 
https://github.com/danilsatchkov/yandex_course/blob/accae30f69288e7e1ba15b68de12a802049656e1/Yandex_course/Error_handling.cpp#L1-L9

**Comment by d13mon** [comment]
Если тектса нет в теле тикета, то значит весь текст размещен в названии тикета

Поясню:

- Порядок инклюдов
https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

 - Также лучше отсортировать по алфавиту в рамках каждой группы.

 - И убрать то что не используется.

Если инклюд не используется в конкретном файле, значит там не нужен.
