### ISSUE TITLE
⚠️FORMAT: нарушено форматирование: std:: string& str

### ISSUE THREAD

**Issue by d13mon** [danilsatchkov/yandex_course#30]
https://github.com/danilsatchkov/yandex_course/blob/accae30f69288e7e1ba15b68de12a802049656e1/Yandex_course/Error_handling.cpp#L72

Я настаиваю на более аккуратном написании кода

**Comment by danilsatchkov** [comment]
Я вот не понимаю почему так, у меня в Visual Studio выглядит вот так:

 
From: Dmitrii Kuchinskii ***@***.***> 
Sent: Sunday, May 16, 2021 3:06 PM
To: danilsatchkov/yandex_course ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [danilsatchkov/yandex_course] ⚠️FORMAT: нарушено форматирование: std:: string& str (#30)
 
https://github.com/danilsatchkov/yandex_course/blob/accae30f69288e7e1ba15b68de12a802049656e1/Yandex_course/Error_handling.cpp#L72
Я настаиваю на более аккуратном написании кода

**Comment by d13mon** [comment]
Проверьте вашу IDE, что она преобразует табы в пробелы (как правило можно настроить)
Табы часто отображаются некорректно. Нам нужно именно 4 пробела, а не табуляция

**Comment by danilsatchkov** [comment]
Да, да, я проверял до этого, но оказалось что в Студии надо в двух местах поменять, если проект уже текущий. Сегодня пересдам.
