### ISSUE TITLE
⚠️FORMAT: нарушено форматирование: после { не ставится пустая строка

### ISSUE THREAD

**Issue by d13mon** [danilsatchkov/yandex_course#33]
https://github.com/danilsatchkov/yandex_course/blob/1759c5096e7051a365b8e9a6b58e7eeacf35be8e/Yandex_course/SearchServer.cpp#L219-L221

**Comment by danilsatchkov** [comment]
Тогда мне нужно пояснение вот по этому Вашему предыдущему комментарию. Он меня капитально запутал. Раньше я не ставил, но... Здесь объявляется функция.:
"Не жадничайте с пустыми строками. Вставляйте всегда пустые строки между определениями глобальных функций, классов, констант, typedef'ов, include'ов, между объявлениями методов и функций, между реализациями функций, между объявлениями классов и реализациями функций и т.д."
 
 
From: Dmitrii Kuchinskii ***@***.***> 
Sent: Monday, May 24, 2021 4:13 PM
To: danilsatchkov/yandex_course ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [danilsatchkov/yandex_course] ⚠️FORMAT: нарушено форматирование: после { не ставится пустая строка (#33)
 
https://github.com/danilsatchkov/yandex_course/blob/1759c5096e7051a365b8e9a6b58e7eeacf35be8e/Yandex_course/SearchServer.cpp#L219-L221
